config/routes.rb
Rails.application.routes.draw do
  resources :chans

   root 'chans#index'

end

app/models/chan.rb
class Chan < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chans_controller.rb
class ChansController < ApplicationController
  before_action :set_chan, only: [:show, :edit, :update, :destroy]

  # GET /chans
  # GET /chans.json
  def index
    @chans = Chan.all
  end

  # GET /chans/1
  # GET /chans/1.json
  def show
  end

  # GET /chans/new
  def new
    @chan = Chan.new
  end

  # GET /chans/1/edit
  def edit
  end

  # POST /chans
  # POST /chans.json
  def create
    @chan = Chan.new(chan_params)

    respond_to do |format|
      if @chan.save
        format.html { redirect_to @chan, notice: 'Chan was successfully created.' }
        format.json { render :show, status: :created, location: @chan }
      else
        format.html { render :new }
        format.json { render json: @chan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chans/1
  # PATCH/PUT /chans/1.json
  def update
    respond_to do |format|
      if @chan.update(chan_params)
        format.html { redirect_to @chan, notice: 'Chan was successfully updated.' }
        format.json { render :show, status: :ok, location: @chan }
      else
        format.html { render :edit }
        format.json { render json: @chan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chans/1
  # DELETE /chans/1.json
  def destroy
    @chan.destroy
    respond_to do |format|
      format.html { redirect_to chans_url, notice: 'Chan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chan
      @chan = Chan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chan_params
      params.fetch(:chan, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chans_helper.rb
module ChansHelper
end

app/views/chans/_form.html.erb
<%= form_for(@chan) do |f| %>
  <% if @chan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chan.errors.count, "error") %> prohibited this chan from being saved:</h2>

      <ul>
      <% @chan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chans/edit.html.erb
<h1>Editing Chan</h1>

<%= render 'form' %>

<%= link_to 'Show', @chan %> |
<%= link_to 'Back', chans_path %>

app/views/chans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chans</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chans.each do |chan| %>
      <tr>
        <td><%= link_to 'Show', chan %></td>
        <td><%= link_to 'Edit', edit_chan_path(chan) %></td>
        <td><%= link_to 'Destroy', chan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chan', new_chan_path %>

app/views/chans/new.html.erb
<h1>New Chan</h1>

<%= render 'form' %>

<%= link_to 'Back', chans_path %>

app/views/chans/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_chan_path(@chan) %> |
<%= link_to 'Back', chans_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gaypage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>